main: crimsonwarpedcraft.exampleplugin
name: Jenny Plugin
version: "1.0"
api-version: "1.12.2" # Use 1.21 for the latest stable Paper API
author: secret
description: hehe
depend: [Citizens] # Critical: This prevents errors when accessing SkinTrait
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
    aliases: [example]
permissions:
  example.test:
    description: DESCRIPTION
    default: true
  example.*:
    description: Grants all other permissions
    default: false
    children:
      example.test: true
