name: JennyPlugin
version: 1.0
main: crimsonwarpedcraft.exampleplugin.ExamplePlugin
author: secret
description: Summoning plugin with Citizens dependency
depend: [Citizens]

commands:
  jenny:
    description: Summon Jenny
    usage: /<command>
    aliases: [jspawn]
    permission: example.test
  ex:
    description: Base command for EXAMPLE
    usage: /ex help
    aliases: [example]

permissions:
  example.test:
    description: Allows you to use /jenny
    default: true
  example.*:
    description: Grants all example permissions
    default: op
    children:
      example.test: true
